spring.application.name=usersapi

spring.datasource.url=jdbc:mysql://persons-db.c1a8a6yu6cd5.us-east-2.rds.amazonaws.com:3306/persons-db
spring.datasource.username=admin
spring.datasource.password=1234567890Jj#

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update